const infos = [
    {
      id: 1,
      imgSrc: "./jaqueta.png",
      tags: ["Camisetas"],
      nome: "Jaqueta",
      descricao: "Adicione um pouco de energia ao seu guarda-roupa de inverno com esta jaqueta vibrante...",
      preco: 120.00,
      botão:"Adicionar ao carrinho",
    },
    {
      id: 2,
      imgSrc: "./chapeu.png",
      tags: ["Acessórios"],
      nome: "Gorro Preto",
      descricao: "O gorro Next.js chegou! Esta beldade bordada tem um ajuste confortável que garante que...",
      preco: 45.00,
      botão:"Adicionar ao carrinho",
    },
    {
      id: 3,
      imgSrc: "./mascara.png",
      tags: ["Acessórios"],
      nome: "Máscara",
      descricao: "Esta máscara facial durável é feita de duas camadas de tecido tratado e possui presilhas...",
      preco: 15.00,
      botão:"Adicionar ao carrinho",
    },
    {
      id: 4,
      imgSrc: "./camisa.png",
      tags: ["Camisetas"],
      nome: "Camisa Preta Basic",
      descricao: "Esta t-shirt é imprescindível no seu guarda-roupa, combinando o caimento intemporal de...",
      preco: 70.00,
      botão:"Adicionar ao carrinho",
    },
    {
      id: 5,
      imgSrc: "./camisa2.png",
      tags: ["Camisetas"],
      nome: "Camisa manga curta",
      descricao: "Agora você encontrou a camiseta básica do seu guarda-roupa. É feito de um mais grosso...",
      preco: 70.00,
      botão:"Adicionar ao carrinho",
    },
    {
      id:6 ,
      imgSrc: "./jaqueta2.png",
      tags: ["Camisetas"],
      nome: "Jaqueta Corta-vento",
      descricao: "Proteja-se dos elementos com esta jaqueta embalável Champion. Esta jaqueta de poliést...",
      preco: 120.00,
      botão:"Adicionar ao carrinho",
    }
  ];